### ISSUE TITLE
Not working with 7.08

### ISSUE THREAD

**Issue by discxrd** [itselectroz/brawlhalla-replay-reader#1] opened 2023-06-13 17:20 UTC
Command: `replay-reader export -o out.json latest`
Result: `Error: Unknown replay read state: 0`

**Comment by kukkich** [comment] 2023-06-22 08:59
It really works, the problem is that the old version is on npm. I found that there is a problem due to the developers added fanfare at the end of the match, which takes up a few extra bytes. In the current version, which is on GitHub, these bytes are read
npm version:
![image](https://github.com/itselectroz/brawlhalla-replay-reader/assets/79147853/07722e78-16da-4cb5-9db3-277bf7132547)
GitHub version:
![image](https://github.com/itselectroz/brawlhalla-replay-reader/assets/79147853/01f9ac99-b5b3-48fe-803e-5a682cc9f057)
However, while writing this comment, I noticed that everything is in order in ReplayData.ts in npm, the problem is only in the .js version of the file

**Comment by itselectroz** [comment] 2024-02-15 18:11
This should be fixed now.

**Closed as completed by itselectroz** 2024-02-15 18:11 UTC
